export * from './home/home';
export * from './user-account/user-account.component';
export * from './menu/menu';
export * from './history/history';
export * from './absolute-header';
export * from './about-us/about-us';
export * from './orders-register/orders-register';
export * from './add-cars/add-cars'
export * from './addresses/addresses';
export * from './add-address/add-address'
export * from "./orders-page/orders-page";
export * from './map/map';
export * from './orders-list/orders-list';
export * from './complete-order/complete-order'
export * from './order-address/order-address';
export * from './orders-history/orders-history';
export * from './orders-history/barrel-orders';
export * from './settings/settings';
export * from './phone-call';
export * from './services-and-prices/services-and-prices';

